- hosts: web
  become: true

  tasks:
    - name: create a directory on node01
      file:
        path: ./icici-dir
        state: directory
      register: dir_status
    - name: print post success
      debug:
        msg: "Dir created"
      when: dir_status.changed



